### ISSUE TITLE
Loading class com.starmicronics.starioextension.s was unsuccessful

### ISSUE THREAD

**Issue by RosilBelli** [EddyVerbruggen/nativescript-star-printer#17]
I have a very simple code on my page trying to use this plugin, but nothing is loaded.
I looked at other issues where this kind of message appears, but also nothing helped me to overcome this issue.
My project is running with NS 4.2 plus the 2.0 vue-cli-template and for Android only.

The only code I'm trying to execute is:

```js
var StarPrinterPlugin = require("nativescript-star-printer");

methods: {
      printItem(item) {
            let commands = new StarPrinterPlugin .SPCommands()
               .text(this.$moment().format('DD/MM/YYYY h:mm a ')).newLine()
               .textBold(item.name).newLine()
               .newLine()
               .newLine()
               .newLine()
               .cutPaper();

            this.starPrinter.print({
               portName: this.printerPortName,
               commands: commands
            }); //The issue title error message happens after trying to execute this print method.
         }
},

mounted() {
         this.starPrinter = new StarPrinterPlugin.StarPrinter();
         console.log('Mounted: ', JSON.stringify(this.starPrinter)); // Prints and empty object '{}'
         this.starPrinter.searchPrinters().then(
            (printers) => {
               this.printerPortName = printers[0].portName;
               console.log('success!');
            }, (err) => {
               console.log(err);
            });

}
```

I really don't know what else I can do to resolve this issue.

**Comment by EddyVerbruggen** [comment]
You're not really telling me what the error is you're seeing. Does the demo app work for you?

**Comment by RosilBelli** [comment]
I cloned the entire repository and tried to run the demo but I got the error below: (after a first almost successful execution)

```bash
> @ start-android-bundle D:\PROJETOS\_TMP\STAR DEMO\nativescript-star-printer-master\demo
> npm run ns-bundle --android --run-app


> @ ns-bundle D:\PROJETOS\_TMP\STAR DEMO\nativescript-star-printer-master\demo
> ns-bundle

Running tns prepare...
Skipping prepare.
Running webpack for android...
D:\PROJETOS\_TMP\STAR DEMO\nativescript-star-printer-master\demo\node_modules\webpack\bin\webpack.js:323
                throw e;
                ^

TypeError: Cannot read property 'emit' of undefined
    at NativeScriptWorkerPlugin.exports.NativeScriptWorkerPlugin.NativeScriptWorkerPlugin.apply (D:\PROJETOS\_TMP\STAR DEMO\nativescript-star-printer-master\demo\node_modules\nativescript-worker-loader\NativeScriptWorkerPlugin.js:9:24)
    at Compiler.apply (D:\PROJETOS\_TMP\STAR DEMO\nativescript-star-printer-master\demo\node_modules\tapable\lib\Tapable.js:375:16)
    at webpack (D:\PROJETOS\_TMP\STAR DEMO\nativescript-star-printer-master\demo\node_modules\webpack\lib\webpack.js:32:19)
    at processOptions (D:\PROJETOS\_TMP\STAR DEMO\nativescript-star-printer-master\demo\node_modules\webpack\bin\webpack.js:313:14)
    at Object.<anonymous> (D:\PROJETOS\_TMP\STAR DEMO\nativescript-star-printer-master\demo\node_modules\webpack\bin\webpack.js:373:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
child process exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ ns-bundle: `ns-bundle`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ ns-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rosil\AppData\Roaming\npm-cache\_logs\2018-11-14T17_59_39_712Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start-android-bundle: `npm run ns-bundle --android --run-app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start-android-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rosil\AppData\Roaming\npm-cache\_logs\2018-11-14T17_59_39_811Z-debug.log
`

**LOG FILE:**

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Rosil\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'ns-bundle',
1 verbose cli   '--android',
1 verbose cli   '--run-app' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prens-bundle', 'ns-bundle', 'postns-bundle' ]
5 info lifecycle @~prens-bundle: @
6 info lifecycle @~ns-bundle: @
7 verbose lifecycle @~ns-bundle: unsafe-perm in lifecycle true
8 verbose lifecycle @~ns-bundle: PATH: C:\Users\Rosil\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\PROJETOS\_TMP\STAR DEMO\nativescript-star-printer-master\demo\node_modules\.bin;C:\Users\Rosil\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\PROJETOS\_TMP\STAR DEMO\nativescript-star-printer-master\demo\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files\Git\cmd;C:\Program Files (x86)\OpenSSH\bin;C:\Users\Rosil\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;C:\Android\android-sdk\tools;C:\Android\android-sdk\platform-tools;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Java\jdk1.8.0_172\bin;C:\Program Files\nodejs\;C:\Users\Rosil\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\Rosil\AppData\Local\Microsoft\WindowsApps;C:\Users\Rosil\AppData\Roaming\npm;C:\Users\Rosil\AppData\Local\Programs\Fiddler
9 verbose lifecycle @~ns-bundle: CWD: D:\PROJETOS\_TMP\STAR DEMO\nativescript-star-printer-master\demo
10 silly lifecycle @~ns-bundle: Args: [ '/d /s /c', 'ns-bundle' ]
11 silly lifecycle @~ns-bundle: Returned: code: 1  signal: null
12 info lifecycle @~ns-bundle: Failed to exec ns-bundle script
13 verbose stack Error: @ ns-bundle: `ns-bundle`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Rosil\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Rosil\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @
15 verbose cwd D:\PROJETOS\_TMP\STAR DEMO\nativescript-star-printer-master\demo
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Rosil\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ns-bundle" "--android" "--run-app"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error @ ns-bundle: `ns-bundle`
22 error Exit status 1
23 error Failed at the @ ns-bundle script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by EddyVerbruggen** [comment]
Sounds like an incompatibility with webpack. I have an idea how to solve it, but can you confirm it works better withoug webpack?

**Comment by RosilBelli** [comment]
Sorry, but I don't know how to do that without webpack. Even though, the project build process, where I'm trying to use this plugin, rely entirely on webpack. 

Is it something regarding webpack version?
