### ISSUE TITLE
Demo compiled successfully but runtime error in phone.

### ISSUE THREAD

**Issue by safalshrestha** [EddyVerbruggen/nativescript-star-printer#18]
Hi,

Thanks for this. I have a problem running on a Pixel 2 XL.

The Demo app compiled and installed run as soon as it runs, it gives an error. I have copied it below, would you be able to help, please?

Is it because I have updated am using version 5? Please let me know if you require anything and I will get back ASAP.

Thanks again.

11-21 20:43:14.898 30872 30872 E AndroidRuntime: 	at com.tns.Runtime.callJSMethodNative(Native Method)
11-21 20:43:14.898 30872 30872 E AndroidRuntime: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
11-21 20:43:14.898 30872 30872 E AndroidRuntime: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
11-21 20:43:14.898 30872 30872 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:970)
11-21 20:43:14.898 30872 30872 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:954)
11-21 20:43:14.898 30872 30872 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:946)
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.demo/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to find module: "nativescript-star-printer", relative to: app/tns_modules/
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2914)
System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
System.err: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
System.err: 	at android.os.Looper.loop(Looper.java:193)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6680)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Failed to find module: "nativescript-star-printer", relative to: app/tns_modules/
System.err: 	at com.tns.Module.resolvePathHelper(Module.java:146)
System.err: 	at com.tns.Module.resolvePath(Module.java:55)
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:954)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:946)
System.err: 	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
System.err: 	at android.app.Activity.performCreate(Activity.java:7144)
System.err: 	at android.app.Activity.performCreate(Activity.java:7135)
System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)

**Comment by safalshrestha** [comment]
I seem to have solved this by removing and adding the star plugin again. However, when I click on search, I just see FOUND[]. The demo doesn't seem to have location permission, just storage. 

Am I missing something? Do I need to add something to this demo before it works?

Thank you.
