### ISSUE TITLE
NativeScript 7+ support not working

### ISSUE THREAD

**Issue by asharghi** [EddyVerbruggen/nativescript-star-printer#32]
Getting the following error on ns core 8.0.3 when searching for printers:

```
(file:///data/data/no.okam.store/files/app/vendor.js:84383:43)
	at StarPrinter.searchPrinters(file:///data/data/no.okam.store/files/app/vendor.js:84382:16)
	at loadPrinters(file:///data/data/no.okam.store/files/app/bundle.js:6878:24)
	at invokeWithErrorHandling(file:///data/data/no.okam.store/files/app/vendor.js:90827:26)
	at invoker(file:///data/data/no.okam.store/files/app/vendor.js:91484:14)
	at _executeCallback(file:///data/data/no.okam.store/files/app/vendor.js:45898:27)
	at TapAndDoubleTapGestureListenerImpl._handleSingleTap(file:///data/data/no.okam.store/files/app/vendor.js:45641:17)
	at TapAndDoubleTapGestureListenerImpl.onSingleTapUp(file:///data/data/no.okam.store/files/app/vendor.js:45610:14)
	at androidOnTouchEvent(file:///data/data/no.okam.store/files/app/vendor.js:45832:41)
	at (file:///data/data/no.okam.store/files/app/vendor.js:39308:25)
	at handleGestureTouch(file:///data/data/no.okam.store/files/app/vendor.js:39307:18)
	at TouchListenerImpl.onTouch(file:///data/data/no.okam.store/files/app/vendor.js:39038:15)
```

This worked before updating from ns 6.5. I have `"nativescript-star-printer": "^4.0.0` installed

**Comment by asharghi** [comment]
It does find the native function, but can't run it:
<img width="845" alt="Screenshot 2021-04-25 at 19 53 32" src="https://user-images.githubusercontent.com/9407896/116003829-1fe14580-a600-11eb-9589-16444abdf8f8.png">

**Comment by asharghi** [comment]
Hi @NathanWalker. Do you have any idea of why this breaks in ns 8? Everything else works fine now in my app (migrated from ns 6.5 to 8), so this isse is the only thing blocking me. Would greatly appreciate any help.

**Comment by asharghi** [comment]
@EddyVerbruggen starting to worry this never will be fixed. Is there anything I can do?

**Comment by asharghi** [comment]
If anybody else is stuck with this I would recommand buying the pro plugin https://plugins.nativescript.rocks/plugin/NativeScript-Print-Star. It works and @NathanaelA is really helpful making sure it works in your app. Don't know what I would do without this
